# class MyCustomError(Exception):
#     pass
# def divide(a, b):
#     if b == 0:
#         raise MyCustomError("You can't divide by zero!")
#     return a / b
# try:
#     result = divide(10, 0)
# except MyCustomError as e:
#     print("Error:", e)
s='hello'
print(s[2])/print(s[-2])
 
 
s='python'
print(s[-7])